### ISSUE TITLE
distillation weights

### ISSUE THREAD

**Issue by lzl2040** [urbste/nanosam2#2]
Thanks for your work! Can you provide the distillation weights, such as resnet18, mobilenet?

**Comment by urbste** [comment]
Hi. Thanks. You can find pretrained nanosam2 checkpoints [here](https://drive.google.com/drive/folders/15wApVHwqJGunjDP_cx5YZDCTEKliOMCQ?usp=sharing). I also updated the readme.md Those are trained for ~10 epochs so you maybe training them for longer will slightly improve the results even more.
